apiVersion: v1
kind: Service
metadata:
  name: fivem-service
  namespace: fivem
spec:
  type: LoadBalancer
  selector:
    app: pw-fivem
  ports:
    - name: fivem-tcp
      port: 30120
      targetPort: 30120
      protocol: TCP
    - name: fivem-udp
      port: 30120
      targetPort: 30120
      protocol: UDP