apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-persistent-volume
  namespace: fivem
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"