version: '3'

services:
  game:
    image: purpleworld/game
    container_name: game
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ".:/opt/cfx-server-data"
      - "./txData:/txData"
      - "./cache:/opt/cfx-server-data/cache"
    ports:
      # Admin dashboard
      - "40120:40120"
      # Game TCP/UDP ports
      - "30120:30120"
      - "30120:30120/udp"
  database-server:
    image: mariadb:latest
    container_name: database-server
    restart: always
    volumes:
      - ./Docker/mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: 'pw'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      - 3308:3306