apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-persistent-volume-claim
  namespace: fivem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage