apiVersion: v1
kind: PersistentVolume
metadata:
  name: asset-persistent-volume
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/resources"