apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: fivem
type: Opaque
stringData:
  USER_NAME: username
  PASSWORD: password
  ROOT_PASSWORD: password
  DATABASE: pw
---
apiVersion: v1
kind: Secret
metadata:
  name: fivem
  namespace: fivem
type: Opaque
stringData:
  STEAM_APIKEY: username
  LICENSE_KEY: password
  TEBEX_SECRET: password