apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gogs-stateful
  name: gogs-stateful
  namespace: fivem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs-stateful
  serviceName: gogs-service
  template:
    metadata:
      labels:
        app: gogs-stateful
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - image: gogs/gogs:latest
        imagePullPolicy: IfNotPresent
        name: gogs-app
        resources: {}
        ports:
          - containerPort: 3000
            name: web
            protocol: TCP
          - containerPort: 28785
            name: ssh
            protocol: TCP
        volumeMounts:
          - name: gogs-storage
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: gogs-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
      storageClassName: do-block-storage