apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  namespace: fivem
  labels:
    app: gogs-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "your-certificate-id"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "example.com"
spec:
  type: LoadBalancer
  selector:
    app: gogs-stateful
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30022
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30009