apiVersion: v1
kind: Service
metadata:
  name: database-cluster-ip-service
  namespace: fivem
spec:
  type: ClusterIP
  selector:
    component: mariadb
  ports:
    - port: 3306
      targetPort: 3306