apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-stateful
  namespace: fivem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb-server"
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb-server
        image: mariadb:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mariadb-storage
            mountPath: /var/lib/mysql
        env:
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: DATABASE
                optional: false
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: ROOT_PASSWORD
                optional: false
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: USER_NAME
                optional: false
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: PASSWORD
                optional: false
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: do-block-storage