apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service-deployment
  namespace: fivem
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mariadb
  template:
    metadata:
      labels:
        component: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
              subPath: mysql
      env:
        - name: SQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: SQLPASSWORD
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim