apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  namespace: fivem
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"