apiVersion: v1
kind: PersistentVolume
metadata:
  name: pw-database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"